//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.AMIS.CORE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.AMIS.CORE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khoản thu.
        /// </summary>
        internal static string Account_Name {
            get {
                return ResourceManager.GetString("Account_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng đã tồn tại trên hệ thống!..
        /// </summary>
        internal static string Customer_Code_Exists_msg {
            get {
                return ResourceManager.GetString("Customer_Code_Exists_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng không được phép để trống!..
        /// </summary>
        internal static string Customer_Code_Null_msg {
            get {
                return ResourceManager.GetString("Customer_Code_Null_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID khách hàng không được phép để trống!..
        /// </summary>
        internal static string CustomerId_Null_msg {
            get {
                return ResourceManager.GetString("CustomerId_Null_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đã tồn tại trong hệ thống, vui lòng kiểm tra lại.
        /// </summary>
        internal static string Duplicate_msg {
            get {
                return ResourceManager.GetString("Duplicate_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã tồn tại trên hệ thống!..
        /// </summary>
        internal static string Email_Exists_msg {
            get {
                return ResourceManager.GetString("Email_Exists_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email chưa đúng định dạng!..
        /// </summary>
        internal static string Email_Invalid_msg {
            get {
                return ResourceManager.GetString("Email_Invalid_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên.
        /// </summary>
        internal static string Employee_Code {
            get {
                return ResourceManager.GetString("Employee_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị phân trang không được phép nhận giá trị âm.
        /// </summary>
        internal static string Invalid_Paging_number {
            get {
                return ResourceManager.GetString("Invalid_Paging_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : số kí tự không được quá.
        /// </summary>
        internal static string Max_length_msg {
            get {
                return ResourceManager.GetString("Max_length_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001.
        /// </summary>
        internal static string MISACode {
            get {
                return ResourceManager.GetString("MISACode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS.
        /// </summary>
        internal static string MS {
            get {
                return ResourceManager.GetString("MS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS0.
        /// </summary>
        internal static string MS0 {
            get {
                return ResourceManager.GetString("MS0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS00.
        /// </summary>
        internal static string MS00 {
            get {
                return ResourceManager.GetString("MS00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhà cung cấp.
        /// </summary>
        internal static string Ncc_Code {
            get {
                return ResourceManager.GetString("Ncc_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không được phép để trống.
        /// </summary>
        internal static string Null_msg {
            get {
                return ResourceManager.GetString("Null_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NV-.
        /// </summary>
        internal static string NV_ {
            get {
                return ResourceManager.GetString("NV_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NV-0.
        /// </summary>
        internal static string NV_0 {
            get {
                return ResourceManager.GetString("NV_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NV-00.
        /// </summary>
        internal static string NV_00 {
            get {
                return ResourceManager.GetString("NV_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NV-000.
        /// </summary>
        internal static string NV_000 {
            get {
                return ResourceManager.GetString("NV_000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại đã tồn tại trên hệ thống!..
        /// </summary>
        internal static string PhoneNumber_Exists_msg {
            get {
                return ResourceManager.GetString("PhoneNumber_Exists_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại chưa đúng định dạng!..
        /// </summary>
        internal static string PhoneNumber_Invalid_msg {
            get {
                return ResourceManager.GetString("PhoneNumber_Invalid_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$&quot;.
        /// </summary>
        internal static string Regex_email {
            get {
                return ResourceManager.GetString("Regex_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;^((\+0?1\s)?)\(?\d{3}\)?[\s.\s]\d{3}[\s.-]\d{4}$&quot;.
        /// </summary>
        internal static string Regex_phoneNumber {
            get {
                return ResourceManager.GetString("Regex_phoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;([A-Za-z0-9_-]+)&quot;.
        /// </summary>
        internal static string Regex_searchInput {
            get {
                return ResourceManager.GetString("Regex_searchInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        internal static string Rest {
            get {
                return ResourceManager.GetString("Rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập kí tự không hợp lệ, vui lòng thử lại.
        /// </summary>
        internal static string Search_input_invalid_characters {
            get {
                return ResourceManager.GetString("Search_input_invalid_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã cán bộ.
        /// </summary>
        internal static string Teacher_Code {
            get {
                return ResourceManager.GetString("Teacher_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra vui lòng liên hệ MISA!..
        /// </summary>
        internal static string User_msg {
            get {
                return ResourceManager.GetString("User_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website chưa đúng định dạng !.
        /// </summary>
        internal static string Website_Invalid_msg {
            get {
                return ResourceManager.GetString("Website_Invalid_msg", resourceCulture);
            }
        }
    }
}
